# Use uma imagem base do JDK 11
FROM openjdk:11-jre-slim

# Defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie o arquivo JAR para o contêiner
COPY target/webservice-0.0.1-SNAPSHOT.jar /app/webservice-0.0.1-SNAPSHOT.jar

# Exponha a porta em que sua aplicação irá rodar
EXPOSE 8080

# Comando para rodar a aplicação
CMD ["java", "-jar", "/app/webservice-0.0.1-SNAPSHOT.jar"]