# Use uma imagem base do JDK 17 de uma fonte diferente
FROM eclipse-temurin:17-jre

# Defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie o arquivo JAR para o contêiner
COPY target/webservice-0.0.1-SNAPSHOT.jar /app/webservice-0.0.1-SNAPSHOT.jar

# Comando para executar o JAR
CMD ["java", "-jar", "/app/webservice-0.0.1-SNAPSHOT.jar"]